<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	大家都知道做前端开发的时候最让人头痛的就是处理异步请求的情况，
	在请求到的成功回调函数里继续写函数，长此以往形成了回调地狱。

	
	什么情况下会用到promise?
	一般情况下是有异步操作时，使用promise对异步操作进行封装
	new -> 构造函数(1.保存了一些状态信息  2.执行传入的函数)
	在执行传入的回调函数时，会传入两个参数，resolve，reject，本身又是函数
	成功的时候调用resolve，失败的时候调用reject

	<!-- <script src="vue.js"></script> -->

	<script>
		// new Promise((resolve, reject) => {
		// 	setTimeout(() => {
		// 		resolve();
		// 	}, 1000)
		// }).then(() => {
		// 	console.log('aaaaaa');
		// 	console.log('aaaaaa');
		// 	console.log('aaaaaa');
		// 	console.log('aaaaaa');
		// 	console.log('aaaaaa');
		// 	console.log('aaaaaa');

		// 	return new Promise((resolve, reject) => {
		// 		setTimeout(() => {
		// 			resolve();
		// 		}, 1000)
		// 	})
		// }).then(() => {
		// 	console.log('bbbbbb');
		// 	console.log('bbbbbb');
		// 	console.log('bbbbbb');
		// 	console.log('bbbbbb');
		// 	console.log('bbbbbb');

		// 	return new Promise((resolve, reject) => {
		// 		setTimeout(() => {
		// 			resolve();
		// 		}, 1000)
		// 	})
		// }).then(() => {
		// 	console.log('cccccc');
		// 	console.log('cccccc');
		// 	console.log('cccccc');
		// 	console.log('cccccc');
		// })

		// 第一次网络请求
		new Promise((resolve, reject) => {
			setTimeout(() => {
				resolve('hello world');
			}, 1000)
		}).then((data) => {
			// 第一次代码处理
			console.log(data);
			console.log(data);
			console.log(data);

			// 第二次网络请求
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve('hello Vue.js');
				}, 1000)
			})
		}).then((data) => {
			// 第二次代码处理
			console.log(data);
			console.log(data);
			console.log(data);
			console.log(data);

			// 第三次网络请求
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve('hello node');
				}, 1000)
			})
		}).then((data) => {
			// 第三次代码处理
			console.log(data);
			console.log(data);
			console.log(data);
			console.log(data);

			// 第四次网络请求
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					// resolve('hello python');
					reject('error message');
				}, 1000)
			})
		}).then((data) => {
			console.log(data);
			console.log(data);
			console.log(data);
			console.log(data);
			console.log(data);
		}).catch((err) => {
			console.log(err);
		})
	</script>
</body>
</html>